ALTER TABLE public.equipments
  ADD COLUMN IF NOT EXISTS data_faturamento DATE,
  ADD COLUMN IF NOT EXISTS frete TEXT CHECK (frete IN ('CIF', 'FOB')),
  ADD COLUMN IF NOT EXISTS peso NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS volume NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS observacao TEXT;